#ifndef _SHORTESTPATHERROR_H
#define _SHORTESTPATHERROR_H

#define ERR_LIST_SPATH_NULL 60
#define ERR_NETWORK_NODE_NULL 61
#define ERR_SPATH_NULL 62
#define ERR_SPATH_NODE_NOT_FOUND 63
#define ERR_SPATH_LIST_ITEM_NULL 64
#define ERR_DST_NAME_NULL 65
#endif // _SHORTESTPATHERROR_H
